"""Hidden input rendering for HTMX state sync."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/inputs.ipynb.

# %% auto #0
__all__ = ['render_hidden_inputs', 'build_include_selector']

# %% ../../nbs/components/inputs.ipynb #330fdfc6
from typing import Any, Optional, Tuple

from fasthtml.common import Div, Hidden

from ..core.models import TokenSelectorState
from ..core.html_ids import TokenSelectorHtmlIds

# %% ../../nbs/components/inputs.ipynb #2ebc5b73
def render_hidden_inputs(
    ids:TokenSelectorHtmlIds,                   # HTML IDs for this instance
    state:Optional[TokenSelectorState] = None,  # current state
    oob:bool = False,                           # render with hx-swap-oob
) -> Any:  # Div containing anchor and focus hidden inputs
    """Render hidden inputs for HTMX form submission."""
    anchor = state.anchor if state else 0
    focus = state.focus if state else 0

    anchor_input = Hidden(
        value=str(anchor),
        id=ids.anchor_input,
        name=ids.anchor_input,
        **(dict(hx_swap_oob="true") if oob else {}),
    )
    focus_input = Hidden(
        value=str(focus),
        id=ids.focus_input,
        name=ids.focus_input,
        **(dict(hx_swap_oob="true") if oob else {}),
    )

    return (anchor_input, focus_input)

# %% ../../nbs/components/inputs.ipynb #bd8bb783
def build_include_selector(
    ids:TokenSelectorHtmlIds,  # HTML IDs for this instance
) -> str:  # CSS selector string for hx_include
    """Build a CSS selector for including anchor and focus inputs in HTMX requests."""
    return f"#{ids.anchor_input}, #{ids.focus_input}"
