"""Tokenization utilities for splitting text into tokens and converting between token indices and character positions."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/helpers/tokenizer.ipynb.

# %% auto #0
__all__ = ['count_tokens', 'get_token_list', 'token_index_to_char_position', 'tokenize']

# %% ../../nbs/helpers/tokenizer.ipynb #c161bb62
from typing import Any, List, Optional, Union

from ..core.models import Token

# %% ../../nbs/helpers/tokenizer.ipynb #1cded653
def count_tokens(
    text:str,  # text to count tokens in
) -> int:  # token count
    """Count the number of whitespace-delimited tokens in text."""
    if not text:
        return 0
    return len(text.split())

# %% ../../nbs/helpers/tokenizer.ipynb #71f880db
def get_token_list(
    text:str,  # text to split into tokens
) -> List[str]:  # list of token strings
    """Split text into a list of whitespace-delimited tokens."""
    if not text:
        return []
    return text.split()

# %% ../../nbs/helpers/tokenizer.ipynb #b0f6d4c0
def token_index_to_char_position(
    text:str,         # full text string
    token_index:int,  # 0-based token index
) -> int:  # character position for split
    """Convert a token index to the character position where a split should occur."""
    if token_index <= 0:
        return 0

    words = text.split()
    if token_index >= len(words):
        return len(text)

    # Walk through the original text to find the character position
    # before the word at token_index
    pos = 0
    for i, word in enumerate(words):
        if i == token_index:
            break
        pos += len(word)
        # Advance past whitespace between words
        while pos < len(text) and text[pos] == ' ':
            pos += 1

    return pos

# %% ../../nbs/helpers/tokenizer.ipynb #c4c9d469
def tokenize(
    text_or_tokens:Union[str, List[str]],  # raw text string or pre-tokenized list
    metadata:Optional[List[Any]] = None,   # per-token metadata (must match token count)
) -> List[Token]:  # list of Token objects
    """Convert text or a pre-tokenized list into Token objects."""
    if isinstance(text_or_tokens, str):
        words = get_token_list(text_or_tokens)
    else:
        words = list(text_or_tokens)

    if metadata is not None and len(metadata) != len(words):
        raise ValueError(
            f"metadata length ({len(metadata)}) must match token count ({len(words)})"
        )

    return [
        Token(text=w, index=i, metadata=metadata[i] if metadata else None)
        for i, w in enumerate(words)
    ]
