"""Master IIFE composer for the token selector JS runtime."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/js/core.ipynb.

# %% auto #0
__all__ = ['global_callback_name', 'generate_token_selector_js']

# %% ../../nbs/js/core.ipynb #3dd234c7
from typing import Any, Tuple

from fasthtml.common import Script

from ..core.config import TokenSelectorConfig
from ..core.models import TokenSelectorState
from ..core.html_ids import TokenSelectorHtmlIds
from .navigation import generate_navigation_js
from .display import generate_display_js
from .repeat import generate_key_repeat_js

# %% ../../nbs/js/core.ipynb #bee1f126
_GLOBAL_CALLBACKS = (
    "activate",
    "deactivate",
    "selectGap",
    "selectWord",
    "selectToken",
    "moveToFirst",
    "moveToLast",
)

def global_callback_name(
    prefix:str,    # token selector instance prefix
    callback:str,  # base callback name
) -> str:  # global function name
    """Generate a prefix-unique global callback name."""
    return f"{prefix}_{callback}"

# %% ../../nbs/js/core.ipynb #173e8f33
def _generate_state_init_js(
    config:TokenSelectorConfig,  # config for this instance
    state:TokenSelectorState,    # initial state
) -> str:  # JS code fragment
    """Generate state initialization code."""
    return f"""
    // State
    ns.anchor = {state.anchor};
    ns.focus = {state.focus};
    ns.wordCount = {state.word_count};
    ns.active = false;
    ns.mode = '{config.selection_mode}';
    ns._prevAnchor = -1;
"""

# %% ../../nbs/js/core.ipynb #94cc4f28
def _generate_on_change_js(
    config:TokenSelectorConfig,  # config for this instance
) -> str:  # JS code fragment
    """Generate the on-change callback dispatcher."""
    if config.on_change_callback:
        return f"""
    ns._fireOnChange = function() {{
        if (typeof window['{config.on_change_callback}'] === 'function') {{
            window['{config.on_change_callback}'](ns.anchor, ns.focus, ns.mode);
        }}
    }};
"""
    return """
    ns._fireOnChange = function() {};
"""

# %% ../../nbs/js/core.ipynb #0089ec56
def _generate_activation_js(
    config:TokenSelectorConfig,  # config for this instance
    ids:TokenSelectorHtmlIds,    # HTML IDs
) -> str:  # JS code fragment
    """Generate activate/deactivate functions."""
    return f"""
    ns.activate = function() {{
        ns.active = true;
        // Re-read word count from DOM
        var grid = document.getElementById('{ids.token_grid}');
        if (grid) ns.wordCount = parseInt(grid.dataset.wordCount) || 0;
        // Reset position
        ns.anchor = 0;
        ns.focus = 0;
        // Add key listeners
        document.addEventListener('keydown', ns._handleKeyDown, true);
        document.addEventListener('keyup', ns._handleKeyUp, true);
        ns.updateDisplay();
        ns.updateInputs();
    }};

    ns.deactivate = function() {{
        ns.active = false;
        // Cancel repeat
        if (ns._repeatTimer) {{
            clearTimeout(ns._repeatTimer);
            ns._repeatTimer = null;
        }}
        ns._repeatKey = null;
        ns._repeatShift = false;
        // Remove key listeners
        document.removeEventListener('keydown', ns._handleKeyDown, true);
        document.removeEventListener('keyup', ns._handleKeyUp, true);
    }};
"""

# %% ../../nbs/js/core.ipynb #d62a060d
def _generate_global_callbacks_js(
    config:TokenSelectorConfig,  # config for this instance
) -> str:  # JS code fragment
    """Generate global callback wrappers."""
    lines = []
    for cb_name in _GLOBAL_CALLBACKS:
        global_name = global_callback_name(config.prefix, cb_name)
        lines.append(
            f"    window['{global_name}'] = function() {{ "
            f"if (ns.{cb_name}) ns.{cb_name}.apply(ns, arguments); }};"
        )
    return "\n".join(lines)

# %% ../../nbs/js/core.ipynb #111900aa
def _generate_settle_handler_js(
    config:TokenSelectorConfig,  # config for this instance
    ids:TokenSelectorHtmlIds,    # HTML IDs
) -> str:  # JS code fragment
    """Generate htmx:afterSettle handler for swap resilience.

    Stores the handler reference globally and replaces it on
    re-initialization to avoid stale closure references when
    the IIFE re-runs after HTMX page transitions.
    """
    handler_key = f"_tsSettleHandler_{config.prefix}"
    return f"""
    // HTMX afterSettle: re-read word count and update display
    // Replace old handler to avoid stale closure references
    if (window['{handler_key}']) {{
        document.body.removeEventListener('htmx:afterSettle', window['{handler_key}']);
    }}
    window['{handler_key}'] = function() {{
        var grid = document.getElementById('{ids.token_grid}');
        if (grid && ns.active) {{
            ns.wordCount = parseInt(grid.dataset.wordCount) || 0;
            ns.updateDisplay();
            ns.updateInputs();
        }}
    }};
    document.body.addEventListener('htmx:afterSettle', window['{handler_key}']);
"""

# %% ../../nbs/js/core.ipynb #48c0e44b
def generate_token_selector_js(
    config:TokenSelectorConfig,              # config for this instance
    ids:TokenSelectorHtmlIds,                # HTML IDs
    state:TokenSelectorState = None,         # initial state
    extra_scripts:Tuple[str, ...] = (),      # additional JS to include in the IIFE
) -> Any:  # Script element with the complete IIFE
    """Compose all token selector JS into a single namespaced IIFE."""
    if state is None:
        state = TokenSelectorState()

    # Collect all JS fragments
    fragments = [
        _generate_state_init_js(config, state),
        _generate_on_change_js(config),
        generate_display_js(config, ids),
        generate_navigation_js(config, ids),
        generate_key_repeat_js(config),
        _generate_activation_js(config, ids),
        _generate_global_callbacks_js(config),
        _generate_settle_handler_js(config, ids),
    ]

    # Consumer extra scripts
    if extra_scripts:
        fragments.append("\n".join(extra_scripts))

    body = "\n".join(fragments)
    prefix = config.prefix

    iife = f"""(function() {{
    'use strict';
    window.tokenSelectors = window.tokenSelectors || {{}};
    var ns = window.tokenSelectors['{prefix}'] = {{}};
{body}
}})();"""

    return Script(iife)
