"""Generates JS functions for updating token display state (caret indicators, highlights, dimming, hidden inputs)."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/js/display.ipynb.

# %% auto #0
__all__ = ['generate_display_js']

# %% ../../nbs/js/display.ipynb #4614e222
from cjm_fasthtml_token_selector.core.constants import (
    CARET_INDICATOR_CLS, OPACITY_50_CLS, HIGHLIGHT_CLS,
)
from ..core.config import TokenSelectorConfig
from ..core.html_ids import TokenSelectorHtmlIds

# %% ../../nbs/js/display.ipynb #85e3702e
def _generate_update_inputs_js(
    ids:TokenSelectorHtmlIds,  # HTML IDs
) -> str:  # JS code fragment
    """Generate the hidden input sync function."""
    return f"""
    ns.updateInputs = function() {{
        var anchorEl = document.getElementById('{ids.anchor_input}');
        var focusEl = document.getElementById('{ids.focus_input}');
        if (anchorEl) anchorEl.value = ns.anchor;
        if (focusEl) focusEl.value = ns.focus;
    }};
"""

# %% ../../nbs/js/display.ipynb #9c85ab30
def _generate_gap_display_js(
    ids:TokenSelectorHtmlIds,  # HTML IDs
) -> str:  # JS code fragment
    """Generate gap mode display update function."""
    return f"""
    ns.updateDisplay = function() {{
        var grid = document.getElementById('{ids.token_grid}');
        if (!grid) return;

        // Remove existing caret indicators
        grid.querySelectorAll('.caret-indicator').forEach(function(el) {{ el.remove(); }});

        var tokens = grid.querySelectorAll('.token');
        var prevAnchor = ns._prevAnchor !== undefined ? ns._prevAnchor : -1;

        tokens.forEach(function(token) {{
            var idx = parseInt(token.dataset.tokenIndex);

            // Dimming: tokens before caret
            if (idx < ns.anchor) {{
                if (!token.classList.contains('{OPACITY_50_CLS}')) {{
                    token.classList.add('{OPACITY_50_CLS}');
                }}
            }} else {{
                token.classList.remove('{OPACITY_50_CLS}');
            }}

            // Caret indicator at anchor position
            if (idx === ns.anchor) {{
                var caret = document.createElement('div');
                caret.className = '{CARET_INDICATOR_CLS}';
                token.insertBefore(caret, token.firstChild);
            }}
        }});

        ns._prevAnchor = ns.anchor;
    }};
"""

# %% ../../nbs/js/display.ipynb #90b62704
def _generate_word_display_js(
    ids:TokenSelectorHtmlIds,  # HTML IDs
) -> str:  # JS code fragment
    """Generate word mode display update function."""
    return f"""
    ns.updateDisplay = function() {{
        var grid = document.getElementById('{ids.token_grid}');
        if (!grid) return;

        var tokens = grid.querySelectorAll('.token');

        tokens.forEach(function(token) {{
            var idx = parseInt(token.dataset.tokenIndex);

            if (idx === ns.anchor) {{
                if (!token.classList.contains('{HIGHLIGHT_CLS}')) {{
                    token.classList.add('{HIGHLIGHT_CLS}');
                }}
            }} else {{
                token.classList.remove('{HIGHLIGHT_CLS}');
            }}
        }});
    }};
"""

# %% ../../nbs/js/display.ipynb #f3f54861
def _generate_span_display_js(
    ids:TokenSelectorHtmlIds,  # HTML IDs
) -> str:  # JS code fragment
    """Generate span mode display update function."""
    return f"""
    ns.updateDisplay = function() {{
        var grid = document.getElementById('{ids.token_grid}');
        if (!grid) return;

        // Remove existing caret indicators
        grid.querySelectorAll('.caret-indicator').forEach(function(el) {{ el.remove(); }});

        var tokens = grid.querySelectorAll('.token');
        var lo = Math.min(ns.anchor, ns.focus);
        var hi = Math.max(ns.anchor, ns.focus);

        tokens.forEach(function(token) {{
            var idx = parseInt(token.dataset.tokenIndex);

            // Highlight tokens in range
            if (idx >= lo && idx <= hi) {{
                if (!token.classList.contains('{HIGHLIGHT_CLS}')) {{
                    token.classList.add('{HIGHLIGHT_CLS}');
                }}
            }} else {{
                token.classList.remove('{HIGHLIGHT_CLS}');
            }}

            // Caret at focus position
            if (idx === ns.focus) {{
                var caret = document.createElement('div');
                caret.className = '{CARET_INDICATOR_CLS}';
                token.insertBefore(caret, token.firstChild);
            }}
        }});
    }};
"""

# %% ../../nbs/js/display.ipynb #c782dde5
def generate_display_js(
    config:TokenSelectorConfig,  # config for this instance
    ids:TokenSelectorHtmlIds,    # HTML IDs
) -> str:  # JS code fragment for the IIFE
    """Generate display update and hidden input sync JS functions."""
    display_generators = {
        "gap": _generate_gap_display_js,
        "word": _generate_word_display_js,
        "span": _generate_span_display_js,
    }
    gen = display_generators.get(config.selection_mode, _generate_gap_display_js)
    return _generate_update_inputs_js(ids) + gen(ids)
