"""Generates mode-specific navigation and selection JS functions."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/js/navigation.ipynb.

# %% auto #0
__all__ = ['generate_navigation_js']

# %% ../../nbs/js/navigation.ipynb #386f20ca
from ..core.config import TokenSelectorConfig
from ..core.html_ids import TokenSelectorHtmlIds

# %% ../../nbs/js/navigation.ipynb #7146756c
def _generate_gap_nav_js(
    config:TokenSelectorConfig,  # config for this instance
    ids:TokenSelectorHtmlIds,    # HTML IDs
) -> str:  # JS code fragment
    """Generate gap mode navigation functions."""
    wrap = "true" if config.wrap_navigation else "false"
    return f"""
    ns.moveLeft = function() {{
        if (ns.anchor > 0) {{
            ns.anchor--;
            ns.focus = ns.anchor;
        }} else if ({wrap}) {{
            ns.anchor = ns.wordCount;
            ns.focus = ns.anchor;
        }}
        ns.updateDisplay();
        ns.updateInputs();
        ns._fireOnChange();
    }};

    ns.moveRight = function() {{
        if (ns.anchor < ns.wordCount) {{
            ns.anchor++;
            ns.focus = ns.anchor;
        }} else if ({wrap}) {{
            ns.anchor = 0;
            ns.focus = ns.anchor;
        }}
        ns.updateDisplay();
        ns.updateInputs();
        ns._fireOnChange();
    }};

    ns.selectGap = function(position) {{
        ns.anchor = Math.max(0, Math.min(position, ns.wordCount));
        ns.focus = ns.anchor;
        ns.updateDisplay();
        ns.updateInputs();
        ns._fireOnChange();
    }};

    ns.moveToFirst = function() {{
        ns.anchor = 0;
        ns.focus = ns.anchor;
        ns.updateDisplay();
        ns.updateInputs();
        ns._fireOnChange();
    }};

    ns.moveToLast = function() {{
        ns.anchor = ns.wordCount;
        ns.focus = ns.anchor;
        ns.updateDisplay();
        ns.updateInputs();
        ns._fireOnChange();
    }};
"""

# %% ../../nbs/js/navigation.ipynb #4ef3a24d
def _generate_word_nav_js(
    config:TokenSelectorConfig,  # config for this instance
    ids:TokenSelectorHtmlIds,    # HTML IDs
) -> str:  # JS code fragment
    """Generate word mode navigation functions."""
    wrap = "true" if config.wrap_navigation else "false"
    return f"""
    ns.moveLeft = function() {{
        if (ns.anchor > 0) {{
            ns.anchor--;
            ns.focus = ns.anchor;
        }} else if ({wrap} && ns.wordCount > 0) {{
            ns.anchor = ns.wordCount - 1;
            ns.focus = ns.anchor;
        }}
        ns.updateDisplay();
        ns.updateInputs();
        ns._fireOnChange();
    }};

    ns.moveRight = function() {{
        if (ns.anchor < ns.wordCount - 1) {{
            ns.anchor++;
            ns.focus = ns.anchor;
        }} else if ({wrap}) {{
            ns.anchor = 0;
            ns.focus = ns.anchor;
        }}
        ns.updateDisplay();
        ns.updateInputs();
        ns._fireOnChange();
    }};

    ns.selectWord = function(index) {{
        ns.anchor = Math.max(0, Math.min(index, ns.wordCount - 1));
        ns.focus = ns.anchor;
        ns.updateDisplay();
        ns.updateInputs();
        ns._fireOnChange();
    }};

    ns.moveToFirst = function() {{
        ns.anchor = 0;
        ns.focus = ns.anchor;
        ns.updateDisplay();
        ns.updateInputs();
        ns._fireOnChange();
    }};

    ns.moveToLast = function() {{
        ns.anchor = Math.max(0, ns.wordCount - 1);
        ns.focus = ns.anchor;
        ns.updateDisplay();
        ns.updateInputs();
        ns._fireOnChange();
    }};
"""

# %% ../../nbs/js/navigation.ipynb #7a3c234e
def _generate_span_nav_js(
    config:TokenSelectorConfig,  # config for this instance
    ids:TokenSelectorHtmlIds,    # HTML IDs
) -> str:  # JS code fragment
    """Generate span mode navigation functions."""
    wrap = "true" if config.wrap_navigation else "false"
    return f"""
    ns.moveLeft = function() {{
        if (ns.focus > 0) {{
            ns.focus--;
            ns.anchor = ns.focus;
        }} else if ({wrap} && ns.wordCount > 0) {{
            ns.focus = ns.wordCount - 1;
            ns.anchor = ns.focus;
        }}
        ns.updateDisplay();
        ns.updateInputs();
        ns._fireOnChange();
    }};

    ns.moveRight = function() {{
        if (ns.focus < ns.wordCount - 1) {{
            ns.focus++;
            ns.anchor = ns.focus;
        }} else if ({wrap}) {{
            ns.focus = 0;
            ns.anchor = ns.focus;
        }}
        ns.updateDisplay();
        ns.updateInputs();
        ns._fireOnChange();
    }};

    ns.extendLeft = function() {{
        if (ns.focus > 0) {{
            ns.focus--;
        }}
        ns.updateDisplay();
        ns.updateInputs();
        ns._fireOnChange();
    }};

    ns.extendRight = function() {{
        if (ns.focus < ns.wordCount - 1) {{
            ns.focus++;
        }}
        ns.updateDisplay();
        ns.updateInputs();
        ns._fireOnChange();
    }};

    ns.selectToken = function(index) {{
        ns.focus = Math.max(0, Math.min(index, ns.wordCount - 1));
        ns.updateDisplay();
        ns.updateInputs();
        ns._fireOnChange();
    }};

    ns.selectGap = function(position) {{
        var idx = Math.max(0, Math.min(position, ns.wordCount - 1));
        ns.anchor = idx;
        ns.focus = idx;
        ns.updateDisplay();
        ns.updateInputs();
        ns._fireOnChange();
    }};

    ns.moveToFirst = function() {{
        ns.anchor = 0;
        ns.focus = 0;
        ns.updateDisplay();
        ns.updateInputs();
        ns._fireOnChange();
    }};

    ns.moveToLast = function() {{
        var last = Math.max(0, ns.wordCount - 1);
        ns.anchor = last;
        ns.focus = last;
        ns.updateDisplay();
        ns.updateInputs();
        ns._fireOnChange();
    }};
"""

# %% ../../nbs/js/navigation.ipynb #eb0cbbbb
def generate_navigation_js(
    config:TokenSelectorConfig,  # config for this instance
    ids:TokenSelectorHtmlIds,    # HTML IDs
) -> str:  # JS code fragment for the IIFE
    """Generate mode-specific navigation and selection JS functions."""
    generators = {
        "gap": _generate_gap_nav_js,
        "word": _generate_word_nav_js,
        "span": _generate_span_nav_js,
    }
    gen = generators.get(config.selection_mode, _generate_gap_nav_js)
    return gen(config, ids)
