"""Custom key repeat engine with configurable initial delay, repeat interval, and throttle floor."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/js/repeat.ipynb.

# %% auto #0
__all__ = ['generate_key_repeat_js']

# %% ../../nbs/js/repeat.ipynb #684c3b7a
from ..core.config import TokenSelectorConfig

# %% ../../nbs/js/repeat.ipynb #b02029c9
def _generate_movement_dispatch_js(
    config:TokenSelectorConfig,  # config for this instance
) -> str:  # JS code fragment for the movement dispatcher
    """Generate the key-to-movement dispatch logic."""
    left_key = config.left_key
    right_key = config.right_key
    mode = config.selection_mode

    # Base movement for unmodified keys
    base_dispatch = f"""
        if (key === '{left_key}') return ns.moveLeft;
        if (key === '{right_key}') return ns.moveRight;
"""

    # Shift-modified keys for span extend
    if mode == "span":
        shift_dispatch = f"""
        if (key === '{left_key}') return ns.extendLeft;
        if (key === '{right_key}') return ns.extendRight;
"""
    else:
        shift_dispatch = """
        return null;
"""

    return f"""
    ns._getMovementFn = function(key, shiftKey) {{
        if (shiftKey) {{{shift_dispatch}
        }}
        {base_dispatch}
        return null;
    }};
"""

# %% ../../nbs/js/repeat.ipynb #0122283a
def generate_key_repeat_js(
    config:TokenSelectorConfig,  # config with timing settings
) -> str:  # JS code fragment for the IIFE
    """Generate the custom key repeat engine JS."""
    initial_delay = config.initial_delay
    repeat_interval = config.repeat_interval
    throttle_floor = config.throttle_floor

    dispatch = _generate_movement_dispatch_js(config)

    return dispatch + f"""
    // Key repeat engine state
    ns._repeatTimer = null;
    ns._repeatKey = null;
    ns._repeatShift = false;
    ns._lastMoveTime = 0;

    ns._handleKeyDown = function(e) {{
        if (!ns.active) return;

        var moveFn = ns._getMovementFn(e.key, e.shiftKey);
        if (!moveFn) return;

        e.preventDefault();
        e.stopPropagation();

        // If same key already held, let the timer run
        if (ns._repeatKey === e.key && ns._repeatShift === e.shiftKey) return;

        // Cancel any existing repeat
        if (ns._repeatTimer) {{
            clearTimeout(ns._repeatTimer);
            ns._repeatTimer = null;
        }}

        ns._repeatKey = e.key;
        ns._repeatShift = e.shiftKey;

        // Immediate first movement
        var now = Date.now();
        if (now - ns._lastMoveTime >= {throttle_floor}) {{
            moveFn();
            ns._lastMoveTime = now;
        }}

        // Start repeat after initial delay, then switch to interval
        ns._repeatTimer = setTimeout(function repeatTick() {{
            var fn = ns._getMovementFn(ns._repeatKey, ns._repeatShift);
            if (!fn || !ns.active) {{
                ns._repeatKey = null;
                ns._repeatShift = false;
                return;
            }}
            var tickNow = Date.now();
            if (tickNow - ns._lastMoveTime >= {throttle_floor}) {{
                fn();
                ns._lastMoveTime = tickNow;
            }}
            ns._repeatTimer = setTimeout(repeatTick, {repeat_interval});
        }}, {initial_delay});
    }};

    ns._handleKeyUp = function(e) {{
        if (e.key === ns._repeatKey) {{
            if (ns._repeatTimer) {{
                clearTimeout(ns._repeatTimer);
                ns._repeatTimer = null;
            }}
            ns._repeatKey = null;
            ns._repeatShift = false;
        }}
    }};
"""
