"""Configuration dataclass for token selector initialization."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/config.ipynb.

# %% auto #0
__all__ = ['TokenSelectorConfig']

# %% ../../nbs/core/config.ipynb #f6ca037a
from dataclasses import dataclass, field

from cjm_fasthtml_token_selector.core.constants import (
    SelectionMode,
    DEFAULT_INITIAL_DELAY, DEFAULT_REPEAT_INTERVAL, DEFAULT_THROTTLE_FLOOR,
    DEFAULT_LEFT_KEY, DEFAULT_RIGHT_KEY, DEFAULT_END_TOKEN_TEXT,
)

# %% ../../nbs/core/config.ipynb #ac2efec9
_prefix_counter:int = 0

def _auto_prefix() -> str: # unique prefix string
    """Generate an auto-incrementing unique prefix."""
    global _prefix_counter
    p = f"ts{_prefix_counter}"
    _prefix_counter += 1
    return p

def _reset_prefix_counter() -> None:
    """Reset the prefix counter (for testing only)."""
    global _prefix_counter
    _prefix_counter = 0

# %% ../../nbs/core/config.ipynb #1e20b437
@dataclass
class TokenSelectorConfig:
    """Initialization-time settings for a token selector instance."""
    prefix:str = field(default_factory=_auto_prefix)  # unique instance prefix
    selection_mode:SelectionMode = "gap"  # selection behavior: "gap", "word", or "span"

    # Key repeat engine timing
    initial_delay:int = DEFAULT_INITIAL_DELAY      # ms before first repeat
    repeat_interval:int = DEFAULT_REPEAT_INTERVAL   # ms between repeats
    throttle_floor:int = DEFAULT_THROTTLE_FLOOR     # minimum ms between movements

    # Key mappings (for the internal key repeat engine)
    left_key:str = DEFAULT_LEFT_KEY    # key for leftward navigation
    right_key:str = DEFAULT_RIGHT_KEY  # key for rightward navigation

    # Display
    end_token_text:str = DEFAULT_END_TOKEN_TEXT  # text for the sentinel end token
    show_end_token:bool = True   # whether to show the end token

    # Behavior
    read_only:bool = False       # disable click/keyboard interaction
    wrap_navigation:bool = False # wrap around at boundaries

    # Callbacks
    on_change_callback:str = ""  # JS function name called on selection change
