"""CSS class constants, selection mode type, timing defaults, and key defaults for the token selector."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/constants.ipynb.

# %% auto #0
__all__ = ['SelectionMode', 'OPACITY_50_CLS', 'CARET_INDICATOR_CLS', 'HIGHLIGHT_CLS', 'DEFAULT_INITIAL_DELAY',
           'DEFAULT_REPEAT_INTERVAL', 'DEFAULT_THROTTLE_FLOOR', 'DEFAULT_LEFT_KEY', 'DEFAULT_RIGHT_KEY',
           'DEFAULT_END_TOKEN_TEXT']

# %% ../../nbs/core/constants.ipynb #df733a6c
from typing import Literal

# %% ../../nbs/core/constants.ipynb #8638b95e
from cjm_fasthtml_daisyui.utilities.semantic_colors import bg_dui

from cjm_fasthtml_tailwind.utilities.sizing import w, h
from cjm_fasthtml_tailwind.utilities.layout import position, top, left
from cjm_fasthtml_tailwind.utilities.effects import opacity
from cjm_fasthtml_tailwind.utilities.transitions_and_animation import animate
from cjm_fasthtml_tailwind.utilities.transforms import translate
from cjm_fasthtml_tailwind.core.base import combine_classes

# %% ../../nbs/core/constants.ipynb #37782140
SelectionMode = Literal["gap", "word", "span"]

# %% ../../nbs/core/constants.ipynb #3768030b
OPACITY_50_CLS = str(opacity(50))

# %% ../../nbs/core/constants.ipynb #03b881be
CARET_INDICATOR_CLS = combine_classes(
    "caret-indicator",
    w(0.5), h(5), bg_dui.error,
    position.absolute, left.negative(1), top("1/2"), translate.y.negative("1/2"),
    animate.pulse
)

# %% ../../nbs/core/constants.ipynb #e532f007
HIGHLIGHT_CLS = str(bg_dui.primary.opacity(20))

# %% ../../nbs/core/constants.ipynb #bbd5f285
DEFAULT_INITIAL_DELAY:int = 400   # ms before first repeat
DEFAULT_REPEAT_INTERVAL:int = 80  # ms between repeats
DEFAULT_THROTTLE_FLOOR:int = 50   # minimum ms between movements

# %% ../../nbs/core/constants.ipynb #0eff67fe
DEFAULT_LEFT_KEY:str = "ArrowLeft"
DEFAULT_RIGHT_KEY:str = "ArrowRight"

# %% ../../nbs/core/constants.ipynb #439ee8a2
DEFAULT_END_TOKEN_TEXT:str = "(End)"
