"""Prefix-based HTML ID generator for token selector DOM elements."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/html_ids.ipynb.

# %% auto #0
__all__ = ['TokenSelectorHtmlIds']

# %% ../../nbs/core/html_ids.ipynb #6f0ce5a8
from dataclasses import dataclass

# %% ../../nbs/core/html_ids.ipynb #562b7868
@dataclass
class TokenSelectorHtmlIds:
    """Prefix-based HTML ID generator for token selector DOM elements."""
    prefix:str  # unique instance prefix

    @property
    def container(self) -> str:  # outer wrapper ID
        """Outer token selector wrapper."""
        return f"{self.prefix}-token-selector"

    @property
    def token_grid(self) -> str:  # flex-wrap token container ID
        """Flex-wrap token container."""
        return f"{self.prefix}-token-grid"

    @property
    def anchor_input(self) -> str:  # hidden input for anchor position
        """Hidden input for anchor position."""
        return f"{self.prefix}-anchor"

    @property
    def focus_input(self) -> str:  # hidden input for focus position
        """Hidden input for focus position."""
        return f"{self.prefix}-focus"

    def token(self,
              index:int,  # token position index
             ) -> str:  # individual token span ID
        """Individual token span ID."""
        return f"{self.prefix}-token-{index}"
