"""Prefix-based HTML ID generator for token selector DOM elements."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/html_ids.ipynb.

# %% auto #0
__all__ = ['TokenSelectorHtmlIds']

# %% ../../nbs/core/html_ids.ipynb #00fedd76
from dataclasses import dataclass

# %% ../../nbs/core/html_ids.ipynb #24a81661
@dataclass
class TokenSelectorHtmlIds:
    """Prefix-based HTML ID generator for token selector DOM elements."""
    prefix:str  # unique instance prefix

    @property
    def container(self) -> str:  # outer wrapper ID
        """Outer token selector wrapper."""
        return f"{self.prefix}-token-selector"

    @property
    def token_grid(self) -> str:  # flex-wrap token container ID
        """Flex-wrap token container."""
        return f"{self.prefix}-token-grid"

    @property
    def anchor_input(self) -> str:  # hidden input ID for anchor position
        """Hidden input ID for anchor position (hyphenated, for CSS selectors)."""
        return f"{self.prefix}-anchor"

    @property
    def focus_input(self) -> str:  # hidden input ID for focus position
        """Hidden input ID for focus position (hyphenated, for CSS selectors)."""
        return f"{self.prefix}-focus"

    @property
    def anchor_name(self) -> str:  # form field name for anchor position
        """Form field name for anchor position (underscored, for Python kwargs)."""
        return f"{self.prefix}_anchor"

    @property
    def focus_name(self) -> str:  # form field name for focus position
        """Form field name for focus position (underscored, for Python kwargs)."""
        return f"{self.prefix}_focus"

    def token(self,
              index:int,  # token position index
             ) -> str:  # individual token span ID
        """Individual token span ID."""
        return f"{self.prefix}-token-{index}"
