"""Data models for tokens, render context, and mutable runtime state."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/models.ipynb.

# %% auto #0
__all__ = ['Token', 'TokenRenderContext', 'TokenSelectorState']

# %% ../../nbs/core/models.ipynb #cd8f9e39
from dataclasses import dataclass, field
from typing import Any, Optional

# %% ../../nbs/core/models.ipynb #1a22b1bf
@dataclass
class Token:
    """A single token in the token grid."""
    text:str        # the token text content
    index:int       # 0-based position in the token list
    metadata:Any = None  # optional consumer metadata per token

# %% ../../nbs/core/models.ipynb #a8270e15
@dataclass
class TokenRenderContext:
    """Context passed to per-token styling callbacks."""
    token:Token        # the token being rendered
    is_selected:bool   # whether this token is in the current selection
    is_anchor:bool     # whether this token is at the anchor position
    is_focus:bool      # whether this token is at the focus position
    selection_mode:str  # current selection mode

# %% ../../nbs/core/models.ipynb #84e86d0a
@dataclass
class TokenSelectorState:
    """Mutable runtime state for a token selector instance."""
    anchor:int = 0      # anchor position (gap index or token index)
    focus:int = 0       # focus position (same as anchor in gap/word mode)
    word_count:int = 0  # total number of tokens
    active:bool = False # whether the key repeat engine is active
